import { useMemo, useState } from "react";
import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { AdminButton, AdminCard, AdminField, AdminShell } from "@/components/local-admin-ui";
import { COLORS } from "@/components/app-ui";
import { formatCurrency, usePharmacy } from "@/lib/pharmacy-context";

export default function DebtsScreen() {
  const { debts, addDebt, settleDebt } = usePharmacy();
  const [showForm, setShowForm] = useState(false); const [customerName, setCustomerName] = useState(""); const [phone, setPhone] = useState(""); const [total, setTotal] = useState(""); const [note, setNote] = useState("");
  const outstanding = useMemo(() => debts.reduce((sum, debt) => sum + Math.max(0, debt.total - debt.paid), 0), [debts]);
  const save = () => { const value = Number(total); if (!customerName.trim() || !value || value < 0) return Alert.alert("بيانات ناقصة", "اكتب اسم العميل وقيمة الحساب."); addDebt({ customerName: customerName.trim(), phone: phone.trim() || undefined, total: value, paid: 0, note: note.trim() || undefined }); setCustomerName(""); setPhone(""); setTotal(""); setNote(""); setShowForm(false); Alert.alert("تم حفظ الحساب", "أضيف الحساب إلى سجل الديون المحلي."); };
  const pay = (debtId: string, balance: number) => { Alert.prompt?.("تسجيل سداد", "أدخل المبلغ المدفوع", (value) => { const amount = Number(value); if (amount > 0) settleDebt(debtId, Math.min(balance, amount)); }, "plain-text", String(balance)); if (!Alert.prompt) settleDebt(debtId, balance); };
  return <AdminShell title="ديون العملاء" subtitle="تابع الآجل والمدفوع والمتبقي بسهولة"><AdminCard style={styles.mainCard}><View style={styles.cardHeader}><TouchableOpacity onPress={() => setShowForm((value) => !value)} style={styles.addButton} activeOpacity={0.8}><Text style={styles.addPlus}>+</Text></TouchableOpacity><View style={styles.headingText}><Text style={styles.cardTitle}>ديون العملاء</Text><Text style={styles.cardSubtitle}>إجمالي المديونية: {formatCurrency(outstanding)}</Text></View></View>{showForm ? <View style={styles.form}><AdminField label="اسم العميل" value={customerName} onChangeText={setCustomerName} placeholder="مثال: محمد علي" /><AdminField label="رقم الهاتف (اختياري)" value={phone} onChangeText={setPhone} placeholder="01xxxxxxxxx" keyboardType="phone-pad" /><AdminField label="قيمة الحساب" value={total} onChangeText={setTotal} placeholder="0.00" keyboardType="decimal-pad" /><AdminField label="ملاحظة" value={note} onChangeText={setNote} placeholder="وصف مختصر للحساب" /><AdminButton title="حفظ الحساب" onPress={save} /></View> : null}<View style={styles.list}>{debts.length ? debts.map((debt) => { const balance = Math.max(0, debt.total - debt.paid); const initials = debt.customerName.trim().split(/\s+/).slice(0, 2).map((word) => word[0]).join(""); return <View key={debt.id} style={styles.debtRow}><View style={styles.initials}><Text style={styles.initialsText}>{initials}</Text></View><View style={styles.debtInfo}><Text style={styles.customerName}>{debt.customerName}</Text><Text style={styles.customerMeta}>{debt.paid ? `آخر دفعة: ${formatCurrency(debt.paid)}` : "لم يتم السداد بعد"}</Text>{balance ? <TouchableOpacity onPress={() => pay(debt.id, balance)} style={styles.payButton} activeOpacity={0.8}><Text style={styles.payText}>تسجيل سداد</Text></TouchableOpacity> : null}</View><Text style={[styles.balance, { color: balance ? COLORS.warning : COLORS.primary }]}>{balance ? formatCurrency(balance) : "تم السداد"}</Text></View>; }) : <Text style={styles.empty}>لا توجد حسابات آجلة مسجلة.</Text>}</View></AdminCard></AdminShell>;
}

const styles = StyleSheet.create({ mainCard: { padding: 20, borderRadius: 28 }, cardHeader: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, headingText: { flex: 1, alignItems: "flex-end" }, cardTitle: { color: COLORS.ink, fontSize: 18, fontWeight: "900", textAlign: "right" }, cardSubtitle: { color: COLORS.muted, fontSize: 12, marginTop: 5, textAlign: "right" }, addButton: { width: 58, height: 58, borderRadius: 18, backgroundColor: COLORS.primary, alignItems: "center", justifyContent: "center" }, addPlus: { color: "#FFFFFF", fontSize: 32, lineHeight: 34, fontWeight: "300" }, form: { paddingTop: 15, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: COLORS.border }, list: { gap: 10 }, debtRow: { minHeight: 91, borderRadius: 22, backgroundColor: "#F2F1EE", padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, initials: { width: 48, height: 48, borderRadius: 16, backgroundColor: COLORS.mint, alignItems: "center", justifyContent: "center" }, initialsText: { color: COLORS.primary, fontSize: 15, fontWeight: "900" }, debtInfo: { flex: 1, alignItems: "flex-end" }, customerName: { color: COLORS.ink, fontSize: 14, fontWeight: "900", textAlign: "right" }, customerMeta: { color: COLORS.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, balance: { fontSize: 15, fontWeight: "900", minWidth: 75, textAlign: "left" }, payButton: { marginTop: 7, borderRadius: 10, backgroundColor: COLORS.primary, paddingHorizontal: 10, paddingVertical: 6 }, payText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, empty: { color: COLORS.muted, textAlign: "right", fontSize: 12, paddingVertical: 16 } });
