import { useMemo } from "react";
import { StyleSheet, Text, View } from "react-native";

import { AdminCard, AdminShell, StatTile, adminStyles } from "@/components/local-admin-ui";
import { COLORS } from "@/components/app-ui";
import { formatCurrency, usePharmacy } from "@/lib/pharmacy-context";

export default function ReportsScreen() {
  const { sales, expenses, debts, medications, activeShift } = usePharmacy();
  const salesTotal = useMemo(() => sales.reduce((sum, sale) => sum + sale.total, 0), [sales]);
  const expensesTotal = useMemo(() => expenses.reduce((sum, expense) => sum + expense.amount, 0), [expenses]);
  const debtTotal = useMemo(() => debts.reduce((sum, debt) => sum + Math.max(0, debt.total - debt.paid), 0), [debts]);
  const stockUnits = useMemo(() => medications.reduce((sum, medication) => sum + medication.quantity, 0), [medications]);
  const lowStock = medications.filter((medication) => medication.quantity <= medication.reorderLevel).length;
  const weeklySales = useMemo(() => Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (6 - index)); const next = new Date(day); next.setDate(day.getDate() + 1); return sales.filter((sale) => { const created = new Date(sale.createdAt); return created >= day && created < next; }).reduce((sum, sale) => sum + sale.total, 0); }), [sales]);
  const maxDaily = Math.max(...weeklySales, 1);
  const topProducts = useMemo(() => { const totals = new Map<string, number>(); sales.forEach((sale) => sale.items.forEach((item) => totals.set(item.name, (totals.get(item.name) ?? 0) + item.quantity))); return [...totals.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3); }, [sales]);

  return <AdminShell title="التقارير" subtitle="تابع أداء الصيدلية واتخذ قراراتك اليومية بثقة"><View style={styles.periodRow}><Text style={[styles.period, styles.periodActive]}>أسبوعي</Text><Text style={styles.period}>شهري</Text></View><AdminCard style={styles.hero}><Text style={styles.heroLabel}>إجمالي المبيعات هذا الأسبوع</Text><Text style={styles.heroValue}>{formatCurrency(salesTotal)}</Text><View style={styles.chart}>{weeklySales.map((value, index) => <View key={index} style={styles.barColumn}><View style={[styles.bar, { height: Math.max(12, (value / maxDaily) * 84), backgroundColor: value === Math.max(...weeklySales) && value > 0 ? "#FFFFFF" : "#72C9AC" }]} /><Text style={styles.dayLabel}>{["س", "ج", "خ", "ر", "ث", "ن", "ح"][index]}</Text></View>)}</View></AdminCard><Text style={adminStyles.sectionHeading}>ملخص سريع</Text><View style={styles.statsRow}><StatTile label="صافي قبل المصروفات" value={formatCurrency(salesTotal - expensesTotal)} accent={COLORS.primary} /><StatTile label="ديون متبقية" value={formatCurrency(debtTotal)} accent={COLORS.danger} /></View><View style={styles.statsRow}><StatTile label="وحدات المخزون" value={stockUnits.toLocaleString("ar-EG")} accent={COLORS.warning} /><StatTile label="أصناف تحتاج متابعة" value={lowStock.toLocaleString("ar-EG")} accent={lowStock ? COLORS.danger : COLORS.primary} /></View><Text style={adminStyles.sectionHeading}>الأكثر مبيعًا</Text><AdminCard>{topProducts.length ? topProducts.map(([name, quantity], index) => <View key={name} style={styles.productRow}><Text style={styles.productQuantity}>{quantity.toLocaleString("ar-EG")} وحدة</Text><Text style={styles.productName}>{name}</Text><Text style={styles.rank}>{index + 1}</Text></View>) : <Text style={styles.empty}>لا توجد مبيعات كافية لعرض الترتيب.</Text>}</AdminCard><Text style={adminStyles.sectionHeading}>حالة التشغيل</Text><AdminCard style={{ backgroundColor: activeShift ? "#ECF8F4" : "#FFF8E9", borderColor: activeShift ? "#B9E2D5" : "#F0D99D" }}><Text style={{ color: activeShift ? COLORS.primary : COLORS.warning, fontSize: 14, fontWeight: "900", textAlign: "right" }}>{activeShift ? `وردية مفتوحة · ${activeShift.pharmacistName}` : "لا توجد وردية مفتوحة"}</Text><Text style={{ color: COLORS.ink, fontSize: 11, lineHeight: 18, textAlign: "right", marginTop: 5 }}>{activeShift ? "المبيعات الجديدة مرتبطة بالوردية الحالية." : "ابدأ وردية من قسم الإدارة قبل تسجيل مبيعات جديدة."}</Text></AdminCard></AdminShell>;
}

const styles = StyleSheet.create({ periodRow: { flexDirection: "row-reverse", alignSelf: "flex-end", gap: 9, marginBottom: 14 }, period: { backgroundColor: "#F2F1EE", color: COLORS.muted, borderRadius: 16, paddingHorizontal: 20, paddingVertical: 11, fontSize: 13, fontWeight: "800" }, periodActive: { backgroundColor: COLORS.deep, color: "#82E3C0" }, hero: { backgroundColor: COLORS.primary, borderColor: COLORS.primary, borderRadius: 27, padding: 20, minHeight: 300 }, heroLabel: { color: "#D5F6E8", fontSize: 14, fontWeight: "800", textAlign: "right" }, heroValue: { color: "#FFFFFF", fontSize: 33, fontWeight: "900", textAlign: "right", marginTop: 5 }, chart: { height: 124, marginTop: 17, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingHorizontal: 8 }, barColumn: { height: 124, alignItems: "center", justifyContent: "flex-end", gap: 7 }, bar: { width: 28, borderRadius: 9, minHeight: 12 }, dayLabel: { color: "#D5F6E8", fontSize: 10, fontWeight: "800" }, statsRow: { flexDirection: "row-reverse", gap: 9, marginBottom: 9 }, productRow: { flexDirection: "row-reverse", alignItems: "center", paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: COLORS.border, gap: 10 }, productName: { flex: 1, color: COLORS.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, productQuantity: { color: COLORS.muted, fontSize: 11, fontWeight: "800" }, rank: { width: 24, height: 24, borderRadius: 12, backgroundColor: COLORS.mint, color: COLORS.primary, textAlign: "center", paddingTop: 4, fontSize: 11, fontWeight: "900" }, empty: { color: COLORS.muted, textAlign: "right", fontSize: 12, paddingVertical: 10 } });
