import { useMemo, useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";

import { AdminButton, AdminCard, AdminField, AdminShell, adminStyles } from "@/components/local-admin-ui";
import { COLORS } from "@/components/app-ui";
import { formatCurrency, usePharmacy } from "@/lib/pharmacy-context";

export default function ShiftsScreen() {
  const { shifts, sales, activeShift, startShift, closeShift } = usePharmacy();
  const [pharmacistName, setPharmacistName] = useState("");
  const [openingCash, setOpeningCash] = useState("0");
  const [actualCash, setActualCash] = useState("");
  const [note, setNote] = useState("");
  const shiftSales = useMemo(() => activeShift ? sales.filter((sale) => sale.shiftId === activeShift.id) : [], [activeShift, sales]);
  const shiftRevenue = shiftSales.reduce((sum, sale) => sum + sale.total, 0);
  const expectedCash = (activeShift?.openingCash ?? 0) + shiftSales.filter((sale) => sale.paymentMethod === "نقدي").reduce((sum, sale) => sum + sale.total, 0);
  const handleStart = () => { const ok = startShift(pharmacistName, Number(openingCash) || 0); if (!ok) return Alert.alert("تعذر بدء الوردية", "أدخل اسم الصيدلي وتأكد من عدم وجود وردية مفتوحة."); setPharmacistName(""); setOpeningCash("0"); Alert.alert("تم بدء الوردية", "أصبحت المبيعات الجديدة مرتبطة بهذه الوردية."); };
  const handleClose = () => { const cash = Number(actualCash); if (!activeShift || Number.isNaN(cash) || cash < 0) return Alert.alert("بيانات غير مكتملة", "أدخل النقدية الفعلية عند إغلاق الوردية."); closeShift(activeShift.id, cash, note.trim() || undefined); setActualCash(""); setNote(""); Alert.alert("تم إغلاق الوردية", "تم حفظ المطابقة النقدية ضمن سجل الورديات."); };

  return <AdminShell title="الشيفتات" subtitle="تابع ورديتك وأغلقها بمطابقة نقدية واضحة">{activeShift ? <><AdminCard style={styles.currentCard}><Text style={styles.cardTitle}>الشيفت الحالي</Text><View style={styles.hero}><View style={styles.heroTop}><Text style={styles.heroName}>{activeShift.pharmacistName}</Text><Text style={styles.heroTime}>بدأ {new Date(activeShift.startedAt).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}</Text></View><Text style={styles.heroLabel}>الكاشير المتوقع الآن</Text><Text style={styles.heroValue}>{formatCurrency(expectedCash)}</Text></View><View style={styles.summaryRow}><View style={styles.summaryBox}><Text style={styles.summaryValue}>{formatCurrency(activeShift.openingCash)}</Text><Text style={styles.summaryLabel}>رصيد افتتاحي</Text></View><View style={styles.summaryBox}><Text style={styles.summaryValue}>{formatCurrency(shiftRevenue)}</Text><Text style={styles.summaryLabel}>مبيعات الشيفت</Text></View></View><AdminButton title="تقفيل الشيفت" onPress={handleClose} /></AdminCard><AdminCard><Text style={styles.cardTitle}>مطابقة النقدية</Text><AdminField label="النقدية الفعلية في الدرج" value={actualCash} onChangeText={setActualCash} placeholder="0.00" keyboardType="decimal-pad" /><AdminField label="ملاحظة اختيارية" value={note} onChangeText={setNote} placeholder="أي فرق أو ملاحظة" /></AdminCard></> : <AdminCard><Text style={styles.cardTitle}>بدء شيفت جديد</Text><AdminField label="اسم الصيدلي" value={pharmacistName} onChangeText={setPharmacistName} placeholder="مثال: أحمد محمد" /><AdminField label="الرصيد الافتتاحي" value={openingCash} onChangeText={setOpeningCash} placeholder="0.00" keyboardType="decimal-pad" /><AdminButton title="بدء الشيفت" onPress={handleStart} /></AdminCard>}<Text style={adminStyles.sectionHeading}>سجل الشيفتات</Text>{shifts.length ? shifts.map((shift) => <AdminCard key={shift.id} style={styles.historyCard}><View style={styles.historyRow}><View style={styles.historyText}><Text style={styles.historyName}>{shift.pharmacistName}</Text><Text style={styles.historyMeta}>{new Date(shift.startedAt).toLocaleDateString("ar-EG")} · افتتاحي {formatCurrency(shift.openingCash)}</Text></View><Text style={[styles.historyStatus, { color: shift.closedAt ? COLORS.primary : COLORS.warning }]}>{shift.closedAt ? `فرق ${formatCurrency(shift.difference ?? 0)}` : "مفتوحة"}</Text></View></AdminCard>) : <AdminCard><Text style={styles.empty}>لا توجد شيفتات محفوظة بعد.</Text></AdminCard>}</AdminShell>;
}

const styles = StyleSheet.create({ currentCard: { padding: 20 }, cardTitle: { color: COLORS.ink, fontSize: 16, fontWeight: "900", textAlign: "right", marginBottom: 15 }, hero: { backgroundColor: COLORS.primary, borderRadius: 27, padding: 20, minHeight: 190 }, heroTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, heroName: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, heroTime: { color: "#D5F6E8", fontSize: 11 }, heroLabel: { color: "#D5F6E8", fontSize: 13, fontWeight: "800", textAlign: "right", marginTop: 22 }, heroValue: { color: "#FFFFFF", fontSize: 34, lineHeight: 42, fontWeight: "900", textAlign: "right", marginTop: 4 }, summaryRow: { flexDirection: "row-reverse", gap: 9, marginVertical: 14 }, summaryBox: { flex: 1, minHeight: 64, borderRadius: 20, backgroundColor: "#F2F1EE", padding: 12, alignItems: "flex-end", justifyContent: "center" }, summaryValue: { color: COLORS.ink, fontSize: 14, fontWeight: "900" }, summaryLabel: { color: COLORS.muted, fontSize: 10, marginTop: 3 }, historyCard: { marginBottom: 9 }, historyRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, historyText: { flex: 1, alignItems: "flex-end" }, historyName: { color: COLORS.ink, fontSize: 13, fontWeight: "900" }, historyMeta: { color: COLORS.muted, fontSize: 10, marginTop: 4 }, historyStatus: { fontSize: 11, fontWeight: "900" }, empty: { color: COLORS.muted, fontSize: 12, textAlign: "right" } });
