import { router } from "expo-router";
import { SectionList, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { Badge, Card, COLORS, PageHeader, RoundIcon } from "@/components/app-ui";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ReorderNeed, usePharmacy } from "@/lib/pharmacy-context";
import { ScreenContainer } from "@/components/screen-container";

export default function AlertsScreen() {
  const { reorderNeeds, markReorderOrdered } = usePharmacy();
  const needsAction = reorderNeeds.filter((item) => item.status === "needed");
  const ordered = reorderNeeds.filter((item) => item.status === "ordered");
  const markAll = () => needsAction.forEach((item) => markReorderOrdered(item.medication.id));
  const sections = [
    { title: "تحتاج إعادة طلب", data: needsAction, tone: "warning" as const },
    { title: "بانتظار التوريد", data: ordered, tone: "success" as const },
  ].filter((section) => section.data.length);
  return <ScreenContainer containerClassName="bg-background" className="flex-1"><SectionList sections={sections} keyExtractor={(item) => item.medication.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} renderSectionHeader={({ section }) => <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{section.title}</Text><Badge label={`${section.data.length} صنف`} tone={section.tone} /></View>} renderItem={({ item }) => <ReorderItem item={item} onMarkOrdered={() => markReorderOrdered(item.medication.id)} />} ItemSeparatorComponent={() => <View style={styles.separator} />} ListHeaderComponent={<><PageHeader title="النواقص وإعادة الطلب" subtitle={needsAction.length ? `${needsAction.length} صنف انخفض بسبب المبيعات ويحتاج متابعة` : ordered.length ? "جميع النواقص الحالية قيد التوريد" : "لا توجد أصناف تحتاج إعادة طلب"} /><Card style={styles.infoCard}><RoundIcon name="shippingbox.fill" color={COLORS.primary} background={COLORS.mint} /><View style={styles.infoText}><Text style={styles.infoTitle}>إدارة النواقص من البيع</Text><Text style={styles.infoSubtitle}>عند الضغط على «أضف للطلبية» ينتقل الصنف لانتظار التوريد. إذا انخفضت كميته ببيع جديد، يعود تلقائيًا للنواقص.</Text></View></Card></>} ListFooterComponent={needsAction.length ? <TouchableOpacity onPress={markAll} style={styles.bulkButton} activeOpacity={0.85}><IconSymbol name="truck.box.fill" size={18} color="#82E3C0" /><Text style={styles.bulkButtonText}>تحويل الكل لطلبية واحدة</Text></TouchableOpacity> : null} ListEmptyComponent={<View style={styles.empty}><RoundIcon name="checkmark.circle.fill" color={COLORS.success} background={COLORS.mint} /><Text style={styles.emptyTitle}>المخزون تحت السيطرة</Text><Text style={styles.emptyDetail}>ستظهر هنا الأصناف التي تنخفض إلى حد إعادة الطلب بسبب المبيعات.</Text></View>} /></ScreenContainer>;
}

function ReorderItem({ item, onMarkOrdered }: { item: ReorderNeed; onMarkOrdered: () => void }) {
  const critical = item.medication.quantity <= Math.max(2, Math.floor(item.medication.reorderLevel / 2));
  const isOrdered = item.status === "ordered";
  return <View style={styles.reorderItem}><View style={styles.itemMain}><RoundIcon name="shippingbox.fill" color={isOrdered ? COLORS.success : critical ? COLORS.danger : COLORS.warning} background={isOrdered ? COLORS.mint : critical ? COLORS.softDanger : COLORS.softWarning} /><View style={styles.itemText}><View style={styles.itemTitleRow}><Text style={styles.itemTitle}>{item.medication.name}</Text><Badge label={isOrdered ? "تم الطلب" : item.resumed ? "انخفض مجددًا" : critical ? "نقص حرج" : "نقص ملحوظ"} tone={isOrdered ? "success" : critical ? "danger" : "warning"} /></View><Text style={styles.itemDetail}>المتاح {item.medication.quantity} عبوات · حد إعادة الطلب {item.medication.reorderLevel}</Text></View><TouchableOpacity onPress={() => router.push({ pathname: "/medicine-form", params: { id: item.medication.id } })} style={styles.editButton} activeOpacity={0.75}><IconSymbol name="chevron.left" size={19} color={COLORS.muted} /></TouchableOpacity></View>{isOrdered ? <View style={styles.orderedState}><IconSymbol name="checkmark.circle.fill" size={17} color={COLORS.success} /><Text style={styles.orderedText}>تم تأكيد الطلب — سيعود هذا الصنف للنواقص فقط عند انخفاضه ببيع جديد.</Text></View> : <TouchableOpacity onPress={onMarkOrdered} style={styles.orderButton} activeOpacity={0.85}><IconSymbol name="checkmark.circle.fill" size={18} color="#FFFFFF" /><Text style={styles.orderButtonText}>أضف للطلبية</Text></TouchableOpacity>}</View>;
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 112, flexGrow: 1 }, bulkButton: { minHeight: 58, borderRadius: 21, backgroundColor: COLORS.deep, marginTop: 18, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 }, bulkButtonText: { color: "#82E3C0", fontSize: 13, fontWeight: "900" }, infoCard: { flexDirection: "row-reverse", alignItems: "center", gap: 12, backgroundColor: COLORS.mint, marginBottom: 24 }, infoText: { flex: 1, alignItems: "flex-end" }, infoTitle: { color: COLORS.ink, fontSize: 14, fontWeight: "900", textAlign: "right" }, infoSubtitle: { color: COLORS.muted, fontSize: 11, lineHeight: 17, marginTop: 3, textAlign: "right" }, sectionHeader: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 9 }, sectionTitle: { color: COLORS.ink, fontSize: 16, fontWeight: "900", textAlign: "right" }, reorderItem: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 19, padding: 14 }, itemMain: { flexDirection: "row-reverse", alignItems: "flex-start", gap: 11 }, itemText: { flex: 1, alignItems: "flex-end", minWidth: 0 }, itemTitleRow: { width: "100%", alignItems: "flex-end", gap: 7 }, itemTitle: { color: COLORS.ink, fontSize: 14, lineHeight: 20, fontWeight: "900", textAlign: "right", width: "100%" }, itemDetail: { color: COLORS.muted, fontSize: 11, lineHeight: 17, marginTop: 5, textAlign: "right", alignSelf: "stretch" }, editButton: { padding: 4 }, separator: { height: 12 }, orderButton: { minHeight: 42, borderRadius: 13, backgroundColor: COLORS.primary, marginTop: 13, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 6 }, orderButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, orderedState: { flexDirection: "row-reverse", justifyContent: "flex-end", alignItems: "center", gap: 6, marginTop: 13, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: COLORS.border }, orderedText: { color: COLORS.success, fontSize: 11, fontWeight: "700", textAlign: "right", flex: 1 }, empty: { alignItems: "center", justifyContent: "center", flex: 1, paddingVertical: 55 }, emptyTitle: { color: COLORS.ink, fontSize: 17, fontWeight: "800", marginTop: 13 }, emptyDetail: { color: COLORS.muted, fontSize: 12, lineHeight: 18, marginTop: 5, textAlign: "center" },
});
